version: "3.8"

volumes:
  statics_volume:

services:
  db:
    build: ./postgres_movies/
    image: postgres_movies
    command: ["postgres"]
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./postgres_movies/pg_movies_volume/_data:/var/lib/postgresql/data

  django:
    build:
      context: ./django_admin/
      args:
        - DJANGO_SETTINGS=config.settings.production
    command: bash -c "
                 ./wait-for-it.sh &&
                 python manage.py collectstatic --no-input &&
                 gunicorn -b 0.0.0.0:8000 config.wsgi"
    volumes:
      - statics_volume:/static/
    depends_on:
      - db
  
  nginx:
    build:
      context: ./nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - statics_volume:/data/static:ro
    ports:
      - 80:80
    depends_on:
      - django
    restart: on-failure
    
